### ISSUE TITLE
qfetch 抓取数据时遇到Bad token的错误

### ISSUE THREAD

**Issue by heroghost** [qiniu/qfetch#1]
qfetch 抓取数据时遇到Bad token的错误。windows 64位系统，使用的是qfetch_windows_amd64.exe

**Comment by jemygraw** [comment]
Bad Token 是 ak，sk设置错了，检查一下。

**Comment by heroghost** [comment]
我检查了，是对的。我换了两个账号的ak和sk

**Comment by jemygraw** [comment]
把你的命令贴出来，另外注意不要暴露ak，sk，windows下面的话，参数最好用双引号`"` 而不是单引号`'`
